---
title: "Proposal"
author: "Anthony Oliveri"
date: '2022-07-20'
output: html_document
---
MBAn Student’s Guide to Ross and Ann Arbor
~Live, Laugh, Ross~

Situation and Proposed Solution

	As the first MBAn cohort, with almost every single one of us new to Ann Arbor and the Ross School of Business, we have faced challenges trying to adapt to a new environment. As a result, our group is seeking to help future generations of MBAn’s by creating a detailed guide on Ross and an introduction to the uncontrollable world of business.
	Our book will include different sections (listed below) explaining the transition to Ann Arbor, unspoken as well as established rules for navigating Ross, and other pieces of information that our team members have found useful in the last few weeks. We will accomplish this goal by following the principles outlined in our team charter.

Preliminary Table of Contents

* Intro to Ross/MBAn
* Ross administration
    + Buildings
    + Program directors / deans / professors
* Places to Study 
    + Booking rooms
    + Interview rooms
    + Libraries
    + Winter Garden
* Ross Norms
    + Dress code
        + When to dress up, etc.
    + Timing of classes
* Classes and professors
* Introduction to the CDO
* Eating at Ross (restaurants that are within walking distance)
* Important ross websites
    + Ross recruit, canvas, impact, handshake, my uofmhealth
* UHS / Health services
    + myuofmhealth
* Preparing for Group Projects and Presentations
* Transportation
    + Busses, where to park, biking, preparing for the winter, etc.

Areas to explore/further questions/Next steps

* Interview fellow classmates as well as professors
* Trying out new restaurants and establishments around Ross
* Keep a journal where we write down our daily observations
* Meet with MBAn 501 professors to ask further RMarkdown questions

